name: Deploy stories

on:
  push:
    branches: [master]

jobs:
  deploy_stories:
    name: Deploy stories
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Build stories
        run: yarn storybook:build
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          build_dir: dist
          fqdn: aui.js.org
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
