name: Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      version:
        description: Hotfix package version for prod, 5.7.0-prod-3.5-0 for example.
        required: true

permissions:
  contents: write
  id-token: write

jobs:
  release:
    name: Release
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: yarn
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Create Release Pull Request or Publish to npm
        if: github.event_name == 'push'
        id: changesets
        uses: changesets/action@v1
        with:
          commit: 'chore: release @alauda/ui'
          title: 'chore: release @alauda/ui'
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Release beta
        if: github.event_name == 'pull_request'
        run: sh scripts/release.sh
        env:
          PUBLISH_VERSION: beta

      - name: Set git info
        if: github.event_name == 'workflow_dispatch'
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Release prod
        if: github.event_name == 'workflow_dispatch'
        run: sh scripts/release.sh
        env:
          PUBLISH_VERSION: ${{ github.event.inputs.version }}

      - name: Sync Cnpm
        if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && steps.changesets.outputs.published == 'true')
        run: npx cnpm sync @alauda/ui
