name: Deploy stories

on:
  push:
    branches: [master]

jobs:
  deploy_stories:
    name: Deploy Stories
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Link Yarn global binaries into PATH
        run: echo "$(yarn global bin)" >> $GITHUB_PATH

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Build stories
        run: yarn storybook:build

      - name: Deploy stories
        if: success()
        uses: crazy-max/ghaction-github-pages@v1
        with:
          build_dir: dist
          fqdn: aui.js.org
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
