name: Run tests

on: pull_request

jobs:
  run_unit_test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Corepack Enable
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: yarn

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Run test
        run: npm run test:ci
